name: Windows CI

on:
  push:
    paths-ignore:
      - "*.md"
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 20
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          # cache: 'npm'
          # cache-dependency-path: '**/package-lock.json'

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            ~/AppData/Roaming/npm
            D:/a/node-nodejs-fundamentals/node-nodejs-fundamentals/node_modules
            D:/a/node-nodejs-fundamentals/node-nodejs-fundamentals/package-lock.json
          key: ${{ runner.os }}-node_modules-cache-v1-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-cache-v1-

      - name: Run tests
        run: |
          npm i
          npx tsc
          npx quick-lint-js ./src/**/*.js ./test/**/*.js
          npx c8 -r lcovonly --all --exclude "test/**" node --experimental-test-coverage ./test/all.js
        env:
          NODE_V8_COVERAGE: coverage0
